/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as CommercialIndexRouteImport } from './routes/commercial/index'
import { Route as CommercialDashboardRouteImport } from './routes/commercial/dashboard'
import { Route as CommercialLoginRouteImport } from './routes/commercial/login'
import { Route as CommercialSignupRouteImport } from './routes/commercial/signup'
import { Route as GovernmentIndexRouteImport } from './routes/government/index'
import { Route as GovernmentDashboardRouteImport } from './routes/government/dashboard'
import { Route as ApiPublicAttributeStreamRouteImport } from './routes/api/public/attribute-stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialIndexRoute = CommercialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommercialRoute,
} as any)
const CommercialDashboardRoute = CommercialDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CommercialRoute,
} as any)
const CommercialLoginRoute = CommercialLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CommercialRoute,
} as any)
const CommercialSignupRoute = CommercialSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => CommercialRoute,
} as any)
const GovernmentIndexRoute = GovernmentIndexRouteImport.update({
  id: '/government/',
  path: '/government/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDashboardRoute = GovernmentDashboardRouteImport.update({
  id: '/government/dashboard',
  path: '/government/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttributeStreamRoute =
  ApiPublicAttributeStreamRouteImport.update({
    id: '/api/public/attribute-stream',
    path: '/api/public/attribute-stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/commercial': typeof CommercialRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/commercial/dashboard': typeof CommercialDashboardRoute
  '/commercial/login': typeof CommercialLoginRoute
  '/commercial/signup': typeof CommercialSignupRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/commercial/': typeof CommercialIndexRoute
  '/government/': typeof GovernmentIndexRoute
  '/api/public/attribute-stream': typeof ApiPublicAttributeStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/methodology': typeof MethodologyRoute
  '/commercial/dashboard': typeof CommercialDashboardRoute
  '/commercial/login': typeof CommercialLoginRoute
  '/commercial/signup': typeof CommercialSignupRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/commercial': typeof CommercialIndexRoute
  '/government': typeof GovernmentIndexRoute
  '/api/public/attribute-stream': typeof ApiPublicAttributeStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/commercial': typeof CommercialRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/commercial/dashboard': typeof CommercialDashboardRoute
  '/commercial/login': typeof CommercialLoginRoute
  '/commercial/signup': typeof CommercialSignupRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/commercial/': typeof CommercialIndexRoute
  '/government/': typeof GovernmentIndexRoute
  '/api/public/attribute-stream': typeof ApiPublicAttributeStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/commercial'
    | '/methodology'
    | '/commercial/dashboard'
    | '/commercial/login'
    | '/commercial/signup'
    | '/government/dashboard'
    | '/commercial/'
    | '/government/'
    | '/api/public/attribute-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/methodology'
    | '/commercial/dashboard'
    | '/commercial/login'
    | '/commercial/signup'
    | '/government/dashboard'
    | '/commercial'
    | '/government'
    | '/api/public/attribute-stream'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/commercial'
    | '/methodology'
    | '/commercial/dashboard'
    | '/commercial/login'
    | '/commercial/signup'
    | '/government/dashboard'
    | '/commercial/'
    | '/government/'
    | '/api/public/attribute-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  CommercialRoute: typeof CommercialRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  GovernmentDashboardRoute: typeof GovernmentDashboardRoute
  GovernmentIndexRoute: typeof GovernmentIndexRoute
  ApiPublicAttributeStreamRoute: typeof ApiPublicAttributeStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/': {
      id: '/commercial/'
      path: '/'
      fullPath: '/commercial/'
      preLoaderRoute: typeof CommercialIndexRouteImport
      parentRoute: typeof CommercialRoute
    }
    '/commercial/dashboard': {
      id: '/commercial/dashboard'
      path: '/dashboard'
      fullPath: '/commercial/dashboard'
      preLoaderRoute: typeof CommercialDashboardRouteImport
      parentRoute: typeof CommercialRoute
    }
    '/commercial/login': {
      id: '/commercial/login'
      path: '/login'
      fullPath: '/commercial/login'
      preLoaderRoute: typeof CommercialLoginRouteImport
      parentRoute: typeof CommercialRoute
    }
    '/commercial/signup': {
      id: '/commercial/signup'
      path: '/signup'
      fullPath: '/commercial/signup'
      preLoaderRoute: typeof CommercialSignupRouteImport
      parentRoute: typeof CommercialRoute
    }
    '/government/': {
      id: '/government/'
      path: '/government'
      fullPath: '/government/'
      preLoaderRoute: typeof GovernmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/dashboard': {
      id: '/government/dashboard'
      path: '/government/dashboard'
      fullPath: '/government/dashboard'
      preLoaderRoute: typeof GovernmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attribute-stream': {
      id: '/api/public/attribute-stream'
      path: '/api/public/attribute-stream'
      fullPath: '/api/public/attribute-stream'
      preLoaderRoute: typeof ApiPublicAttributeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommercialRouteChildren {
  CommercialDashboardRoute: typeof CommercialDashboardRoute
  CommercialLoginRoute: typeof CommercialLoginRoute
  CommercialSignupRoute: typeof CommercialSignupRoute
  CommercialIndexRoute: typeof CommercialIndexRoute
}

const CommercialRouteChildren: CommercialRouteChildren = {
  CommercialDashboardRoute: CommercialDashboardRoute,
  CommercialLoginRoute: CommercialLoginRoute,
  CommercialSignupRoute: CommercialSignupRoute,
  CommercialIndexRoute: CommercialIndexRoute,
}

const CommercialRouteWithChildren = CommercialRoute._addFileChildren(
  CommercialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  CommercialRoute: CommercialRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  GovernmentDashboardRoute: GovernmentDashboardRoute,
  GovernmentIndexRoute: GovernmentIndexRoute,
  ApiPublicAttributeStreamRoute: ApiPublicAttributeStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
