import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Trace — Terms & Conditions" },
      { name: "description", content: "Terms and Conditions for the Trace AML platform." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-slate-300 font-sans pb-24">
      <header className="px-6 py-8 border-b border-white/10 flex justify-between items-center">
        <Link to="/" className="text-xl font-bold text-white font-mono">Trace</Link>
      </header>
      <main className="max-w-3xl mx-auto pt-16 px-6">
        <h1 className="text-3xl font-bold text-white mb-8">Terms & Conditions</h1>
        <p className="mb-4">Last Updated: {new Date().toLocaleString("default", { month: "long", year: "numeric" })}</p>
        
        <div className="space-y-8 mt-12 text-sm leading-relaxed text-slate-400">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Nature of the Service</h2>
            <p>
              Trace is an automated heuristic and algorithmic attribution engine designed to assist in blockchain forensics. 
              <strong>This software produces automated investigative leads, NOT definitive legal or compliance determinations.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Limitation of Liability and Accuracy</h2>
            <div className="bg-red-950/30 border border-red-500/20 p-4 rounded-md mb-4 text-red-200">
              A "LOW" risk score or absence of VASP attribution does NOT certify that a wallet is clean, unassociated with illicit activity, or exempt from regulatory reporting obligations.
            </div>
            <p className="mb-2">
              All attributions, path scores, and risk tiers are generated by automated multi-hop BFS heuristics. 
              Trace relies on a fixed, curated public registry of known Virtual Asset Service Providers (VASPs). We do not guarantee exhaustive coverage.
              <strong>Qualified human compliance review is strictly required</strong> prior to filing Suspicious Activity Reports (SARs), freezing assets, or executing regulatory actions based on Trace output.
            </p>
            <p>
              To the maximum extent permitted by applicable law, Trace and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service or reliance on the attribution data provided.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Sanctions and Third-Party Data</h2>
            <p>
              Sanctions screening is powered by the OpenSanctions Community API. While we cover major global watchlists (OFAC, UN, EU, UK HMT), we do not control this third-party feed. Latency in feed updates may result in false negatives. Trace provides these results "as is" without warranty of completeness.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Cross-Chain Bridge Boundaries</h2>
            <p>
              Trace operates strictly on Ethereum Mainnet. When a transaction flow terminates at a cross-chain bridge contract, the trace stops and is marked as exiting to a bridge. This result is inconclusive. Destination-chain attribution is not established by Trace, and users must employ multi-chain investigation tools to follow funds further.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Trace is headquartered, without regard to its conflict of law provisions.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
